### ISSUE TITLE
gather facts does not work if "items" does not exist

### ISSUE THREAD

**Issue by johnatspark1** [joelwking/ansible-f5#2]
Looks like you introduced a small bug when fixing the last one...
On line 136 of icontrol_gather_facts.py you replace key name of 'items' with 'bigip_items'.  Should probably make sure the key 'items' exists first.

**Comment by johnatspark1** [comment]
Here is an example task:
```
      - name: get facts via igf
        icontrol_gather_facts:
            uri: "/mgmt/tm/sys/failover"
            host: "{{ inventory_hostname }}"
            username: "{{ some_username }}"
            password: "{{ some_password }}"


```
And the resulting error:
`File \"/tmp/ansible_RRX4ZR/ansible_module_icontrol_gather_facts.py\", line 136, in get_facts\n    result[\"ansible_facts\"][\"bigip_items\"] = result[\"ansible_facts\"].pop(\"items\")   # replace key name of 'items' with 'bigip_items'\nKeyError: 'items'\n"`

I know very little python, but I'll google around and see if I can figure out how to make that assignment conditional.

Thanks
